name: Java CI with Gradle

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run linter formatter
        run: ./gradlew ktlintFormat
      - name: Run Gradle Check (build, test, lint)
        run: ./gradlew check
        env:
          JDBC_DATABASE_URL: jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgres
