name: linter

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run lint formater
      run: gradlew klintFormat
    - name: Run linter
      run: gradlew klintCheck